# Week 4

## Summary

Yokohama City, located approximately 30-40km away to the south west from the central area of Tokyo, is the capital city of Kanagawa prefecture. With a population of approximately 3.7 million, it is the largest municipality in the country. Yokohama as a port city is known for its leading role in trade, commerce, shipping, shipbuilding internationally, supporting the everyday lives of the Tokyo Metropolitan region [@thecityofyokohamaeuroperepresentativeoffice].

Forming the Tokyo-Yokohama conurbation, Yokohama city has been identified as urban areas with one of the highest risks of natural disasters due to its high exposure to earthquakes and flood risks [@schwarzmichael2014]. Based on these identified risks, the Disaster Risk Prevention Plan set by Yokohama has three pillars: measures against earthquakes, measure against floods and storms, and measures against urban disasters [@yokohamacitydisasterpreventioncouncil2021a]. Here, we would like to focus on measures against earthquakes, due to its proneness to different types of earthquakes and the large scale damage expected [@cityofyokohama2019].

The existing plan is focused on the actions to be taken for an immediate response (comprised of 177 pages), while there has not been as much attention towards the rehabilitation and recovery of the city (comprised of 30 pages). Within this framework, the reconstruction of the city has been minimum amount of attention, briefly mentioning its plans to consider the areas for specific policy implementation, notify the residents, considering the plans for Yokohoma city as a whole and each area [@yokohamacitydisasterpreventioncouncil2021]. In the action strategy based on this plan set for 2013-2022 comprised of three main goals: minimising damage, suppress confusion in the event of an outbreak and protect the lives of citizens, and support victims and promote early recovery, there was no direct mention of City Reconstruction as a target [@thecityofyokohama2013].

In the neighbouring city Tokyo, there have been efforts made for "Pre-reconstruction", which involves considering in advance the modalities, procedures, and execution system for a rapid and well-planned urban reconstruction and sharing the information with residents and administrative staff [@bureauofurbandevelopmenttokyometropolitangovernment2021]. This indicates the importance of having a more well-developed plan for recovery. In addition, in the Sendai Framework for Disaster Risk Reduction, the recovery, rehabilitation and reconstruction phase has been identified as a 'critical opportunity to build back better' [@unitednationsofficefordisasterriskreduction]. It also recognises the phase as allowing further disaster risk reduction to be incorporated in the development measures (ibid.). Therefore, it is crucial for Yokohama city to implement policies that allow for an effective recovery which will make the city more prepared for future disaster not just only earthquakes.

## Applications

Remote sensing data has been used as a proxy of disaster risk in different phases, such as damage, recovery, resilience, and vulnerability [@ghaffarian2018]. Here, we are especially interested in how the data may be used in recovery process. In addition, there are several types of environments where remote-sensing based proxies have been developed (ibid.). This includes physical assessments through investigating built-up aspects, and also non-physical assessments involving economic, social, and natural aspects (ibid.).

One of the potential applications of remote sensing applications is by looking at building removal and reconstruction through very high resolution (VHR) images over multiple time periods. The number of reconstructed buildings can show how much progress has been made in the recovery process [@ghaffarian2018a]. A periodic monitoring of recovery is important to understand the locations where recovery is slow, which will allow for further examination into the reasons for the the delay and implementing targeted measures that tackle the issue. However, it should be noted that while this data may be used for understanding the speed of recovery, investigation into the quality of recovery should be conducted as well, perhaps through field observations [@platt2016]. This will allow for the assessment of functional recovery.

Another potential area of application is looking into spatial connectivity to the central business district, in this case not only the CBD of Yokohama but also Tokyo as it is often considered as a singular urban zone. This involves the usage of satellite imagery for the identification of road networks. According to the study by Contreas *et al* [-@contreras2013], spatial connectivity which is measured by variables such as distance and travel time may be considered as a proxy for post-earthquake recovery due to its relationship with the return of economic functioning.

## Reflections

Researching into the application of remote sensing data in the field of disaster risk reduction was very informative in terms of what areas have been less researched, which also happen to be perhaps payed less attention in policy. According to Ghaffarian *et al* [-@ghaffarian2018b], the theme of recovery has been relatively neglected in the area of disaster risk reduction in comparison to areas of damage and vulnerability. In addition, much of the research with remote sensing data particulary through the usage of small aerial drones, a newer platform for satellite imagery have been applied to landslides or other mass movements, particularly within rural environments [@kucharczyk2021]. Research around earthquakes and disasters in urban areas in general has been less researched (ibid.). Yokohama pushing forward policies for the usage of remote sensing data for the recovery and reconstruction of the city may become a role model for other cities to follow, and allow for more research in the area.
